ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "TensorFlow_lr_schedulers"
  description: "Learning rate schedulers for TensorFlow"
  execute: 
    enabled: false
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: main
  repo-url: https://github.com/patcmiller/TensorFlow_lr_schedulers/
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/patcmiller/TensorFlow_lr_schedulers/
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
